version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    
    ports:
      - 1883:1883

  go-backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mqtt-broker

  react-frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - go-backend